<?php
/**
 * @file
 * Code for the InnovatoriPA Wiki feature.
 */

include_once 'innovatoripa_wiki.features.inc';

function innovatoripa_wiki_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'book':
      if (isset($node->content['links']['book']['#links']['book_printer'])) {
          unset ($node->content['links']['book']['#links']['book_printer']);
      }
      $context = og_context();
      if ($context && isset($node->content['links']['book']['#links']['book_add_child'])) {
          $node->content['links']['book']['#links']['book_add_child']['query']['og_group_ref'] = $context['gid'];
      }
      break;
  }
}

function innovatoripa_wiki_form_book_node_form_alter(&$form, &$form_state, $form_id) {
    $context = og_context();
    if ($context) {
        // per controllare se è un amministratore uso questo permesso
        $is_admin = og_user_access('node', $context['gid'], "update group");
        if (!$is_admin) {
            unset($form['book']['bid']['#options'][0]);
            unset($form['book']['bid']['#options']['new']);
        }
        else {
            unset($form['book']['bid']['#options'][0]);
        }
    }
} 