<?php
/**
 * @file
 * Code for the InnovatoriPA Search engine feature.
 */

include_once 'innovatoripa_search_engine.features.inc';

/**
 * Implements of hook_views_api_alter()
 * 
 *function innovatoripa_search_engine_views_api_alter(&$list) {
 * $list['views']['template path'] = drupal_get_path('module', 'innovatoripa_search_engine') . '/theme/views';
 * }
 * 
 */

/**
 * Implements hook_og_context_negotiation_info().
 *
 * We are adding a new way to set the group context, based on a path like 'group/%/whatever',
 * so group views and custom pages retain the group context.
 */
function innovatoripa_search_engine_og_context_negotiation_info() {
  $providers = array();
  $providers['innovatoripa_og_search'] = array(
    'name' => t('InnovatoriOG Search Group url'),
    'description' => t("Select group context for any url that starts with 'groups/search/%nid'"),
    'callback' => 'innovatoripa_search_engine_search_context_handler_url',
  );
  return $providers;
}

/**
 *  Return true if node/%/path is a group path
 */
function innovatoripa_search_engine_search_context_handler_url() {
  if ((arg(0) == 'groups') && (arg(1) == 'search') && (is_numeric(arg(2)))) {
    $node = node_load(arg(2));
    // this can be false, example after (node/%node/delete)
    if ($node) {
      if (og_is_group('node', $node)) {
        return _group_context_handler_entity('node', $node);
      }
    }
  }
}


/**
 * Implements of hook_form_alter()
 */
function innovatoripa_search_engine_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $context = og_context();
    if ($context) {
      unset($form['custom_search_paths']);
      $form['#submit'][1] = 'innovatoripa_search_engine_search_block_form_submit';
    }
  }
}

function innovatoripa_search_engine_search_block_form_submit($form, &$form_state) {
  $context = og_context();
  if ($context) {
    $gid = $context['gid'];
    $text = $form_state['values']['search_block_form'];
    $url = "groups/search";
    $query = array('search_api_views_fulltext' => $text);
    drupal_goto('groups/search/' . $gid, array('query' => $query));
  }
}

